version: '3.1'

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASES: dev
    ports:
      - '5432:5432'
